-- FUNÇAO DE AGRUPAMENTO COUNT VAI CONTAR A QUANTIDADE DE LINHAS DE ACORDO COM OQ VC PEDIU
-- ESTUDAR PAGINAÇÃO
SELECT 
    COUNT(*) 
FROM
    ALUNOS AS A
-- NOT EXISTS VERIFICAR OQ NAO EXISTE SEM O NOT É QUAIS EXISTEM
-- CROS JOIN ESTUDAR
WHERE NOT EXISTS (SELECT 1 
				  FROM historicos AS H
WHERE A.MAT_ALU = H.MAT_ALU);